name: foin_v2
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
dependencies:
  - python=3.7
  - pip
  - tqdm
  - h5py
  - numpy
  - scipy
  - pandas
  - imageio
  - yaml
  - pyyaml
  - matplotlib
  - cudatoolkit=11.3
  - pytorch=1.8.1
  - torchvision
  - torchaudio
  - nvidia-apex
  - kornia
  - wandb
  - pip:
    - opencv-python

